# Generated by Django 5.0.1 on 2024-11-24 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='status',
            field=models.CharField(choices=[('in-progress', 'In Progress'), ('completed', 'Completed')], default='in-progress', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_artist',
            field=models.BooleanField(default=True),
        ),
    ]
