# Generated by Django 5.0.1 on 2024-11-24 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_artwork_status_alter_user_is_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='categories',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='event',
            name='max_participants',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='requirements',
            field=models.TextField(blank=True),
        ),
    ]
